### ISSUE TITLE
fatal bug in disperse-welcome-folder

### ISSUE THREAD

**Issue by danverde** [byuitechops/disperse-welcome-folder#11]
```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\disperse-welcome-folder\main.js:260
            moveStandardResourcesCallback(null, null);
            ^

TypeError: moveStandardResourcesCallback is not a function
    at moveStandardResourcesContent (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\disperse-welcome-folder\main.js:260:13)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at moveWelcomeContent (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\disperse-welcome-folder\main.js:179:13)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at asyncLib.eachLimit (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\disperse-welcome-folder\main.js:164:13)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:473:16
```

**Comment by danverde** [comment]
This occurred in pathway course 22866

**Comment by sethchilders92** [comment]
I think I fixed this...can you run the tool again on the course to see if it's good? @danverde

**Comment by sethchilders92** [comment]
Now it should be fixed. @danverde

**Comment by csammcgrath** [comment]
The ordering should also be fixed.
