### ISSUE TITLE
PUT request got a 500 response

### ISSUE THREAD

**Issue by danverde** [byuitechops/disperse-welcome-folder#12]
Here's what it looked like:
```
disperse-welco… message                   message: Successfully moved Instructional Videos into the Welcome module from the Resources module
disperse-welco… error                     message: Status Code 500 | PUT | https://byui.instructure.com/api/v1/courses/10927/modules/107813/items/594512 | {"errors":[{"message":"An error occurred.","error_code":"internal_server_error"}],"error_report_id":91266} stack: Error: Status Code 500 | PUT | https://byui.instructure.com/api/v1/courses/10927/modules/107813/items/594512 | {"errors":[{"message":"An error occurred.","error_code":"internal_server_error"}],"error_report_id":91266}
    at Request.request [as _callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:97:19)
    at Request.self.callback (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

It happened on Pathway course 22757  (MATH 100G).
It's possible that the issue has nothing to do with our code, but it's also possible that we're sending a malformed request. You'll have to do some testing to see if it looks like we're making a bad request.

**Comment by danverde** [comment]
@sethchilders92 Any progress on this issue? 
@csammcgrath you looked into this before you left, am I right?

**Comment by sethchilders92** [comment]
I fixed some potential errors, so if you run it then hopefully it'll work without any errors.

**Comment by sethchilders92** [comment]
Ran the tool on the same course with no errors. Closing Issue.
