### ISSUE TITLE
PUT request got a 400 response

### ISSUE THREAD

**Issue by danverde** [byuitechops/disperse-welcome-folder#13]
This happened on ME 231 (17617)

```
Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11342/modules/114840/items/655715 | {"message":"invalid module_id"} stack: Error: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11342/modules/114840/items/655715 | {"message":"invalid module_id"}
    at Request.request [as _callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:97:19)
    at Request.self.callback (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by sethchilders92** [comment]
Should be fixed. I fixed some of the testing for bad moduleItemIds and changed the eachLimit to an eachSeries which hopefully fixed the 400 issue

**Comment by zachintosh** [comment]
ME 231 ran fine. Looks like this is fixed.
