### ISSUE TITLE
PUT got a 400 response

### ISSUE THREAD

**Issue by danverde** [byuitechops/disperse-welcome-folder#14]
It had an invalid moduleID. it happened on Pathway course 22867 (FDREL 250 - RG-- - Online Reference (Gathering)
```
disperse-welco… error                     message: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11637/modules/119732/items/688878 | {"message":"invalid module_id"} stack: Error: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11637/modules/119732/items/688878 | {"message":"invalid module_id"}
    at Request.request [as _callback] (E:\Documents\work\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:98:37)
    at Request.self.callback (E:\Documents\work\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (E:\Documents\work\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (E:\Documents\work\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by sethchilders92** [comment]
I think I fixed it... @danverde

**Comment by sethchilders92** [comment]
Resolved. I ran it on this course and fixed the issue @danverde
