### ISSUE TITLE
Disperse Welcome Folder - Another 400 Error

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/disperse-welcome-folder#15]
```disperse-welco… error                     message: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11721/modules/121328/items/700866 | {"message":"invalid module_id"} stack: Error: Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11721/modules/121328/items/700866 | {"message":"invalid module_id"}
    at Request.request [as _callback] (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:98:37)
    at Request.self.callback (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)```

**Comment by zachintosh** [comment]
Occurred twice in course 17618

**Comment by sethchilders92** [comment]
I think I fixed it... @zlw11063

**Comment by sethchilders92** [comment]
Everything is working now
